### ISSUE TITLE
Readme.md outdated

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.runtime#13]
https://github.com/eclipse-platform/eclipse.platform.runtime#readme

shows links to old bugtracker, old git

**Comment by jukzi** [comment]
also CONTRIBUTING, CONTRIBUTING.md

can they just be deleted all together? Those from parent https://github.com/eclipse-platform should be enough.

**Comment by mickaelistria** [comment]
+1 to delete outdated stuff when there is a better source somewhere else.

**Comment by jukzi** [comment]
I deleted the outdated file in order to let the files from the common .github repository 
https://github.com/eclipse-platform/.github
should be shown on.
But they are not shown on the subproject https://github.com/eclipse-platform/eclipse.platform.runtime
They are only shown on https://github.com/eclipse-platform :-(
Anybody knows why / how to resolve that?

**Comment by EclipseNewb** [comment]
Well, the Contribution.md from parent is shown for non-committers. Just the Readme.md is not taken from parent.
