### ISSUE TITLE
-Dosgi.dataAreaRequiresExplicitInit=true doesn't work anymore

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.runtime#35]
This was originally created as https://github.com/eclipse-equinox/equinox.bundles/issues/21.

While reviewing https://github.com/eclipse-platform/eclipse.platform.resources/pull/71 I've found, that I'm able to silently init a workspace (with default value) without specifying workspace location explicitly via prompt or `-data` argument, even if `-Dosgi.dataAreaRequiresExplicitInit=true` is set in eclipse.ini.

This is a regression, so bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=514333 is back.

I'm investigating where it was broken... 4.19 is OK, 4.20 is broken...

OK, regression is coming from 
- bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=572128 
- patch https://git.eclipse.org/r/c/platform/eclipse.platform.resources/+/178144 
- commit https://github.com/eclipse-platform/eclipse.platform.resources/commit/a8a8d824145ea1f309eb0b4ade83995544eead50

Ironically, commit message was `The start code for the plugin can be migrated to run inside Workspace
without changing existing behaviour.`...

The root cause is the default initialization order of `LocalMetaArea` and `WorkspaceRoot` objects after the patch above. If the `WorkspaceRoot` is created first, it silently initializes default location for workspace. I will push a patch.

**Comment by iloveeclipse** [comment]
> I though there is no default for the instance (aka workspace) location defined at all so what default is then used here

Unfortunately exactly that is the problem. BasicLocation, if not explicitly set, resolves to default in org.eclipse.osgi.internal.location.BasicLocation.getURL(), and default in Equinox is defined as userhome/workspace, see org.eclipse.osgi.internal.location.EquinoxLocations.EquinoxLocations().

For the rest, see explanation in #36 commit.

**Comment by laeubi** [comment]
Is `osgi.dataAreaRequiresExplicitInit` something I would use for debugging? Or is it expsected that users set this or defined by EEPs?

**Comment by iloveeclipse** [comment]
> Is osgi.dataAreaRequiresExplicitInit something I would use for debugging?

Not really.

> Or is it expsected that users set this or defined by EEPs?

It is expected to be set by the final product that expectes user to select the workspace location and to make sure no code would init workspace to some (unexpected by user) default location.
