### ISSUE TITLE
Add a method EclipseContextFactory.getServiceContext(Class<?>) method

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.runtime#43]
Currently one needs to pass a `BundleContext` to `EclipseContextFactory.getServiceContext` to get an OSGi Service Context.
In case such one is not at hand, it would be useful to let it determine it by a context class and adding some sanity checks.

**Comment by HannesWell** [comment]
We could go even one step further and add a no-argument overload and obtains the caller-class using the StackWalker-API, for example like Status is doing it:
https://github.com/eclipse-equinox/equinox.bundles/blob/f3c4cedb47cf2cfc007b55161f1954fd01d55551/bundles/org.eclipse.equinox.common/src/org/eclipse/core/runtime/Status.java#L166

That class could then be passed to the new class-argument overload.

**Comment by laeubi** [comment]
Sure, just open A PR if you like, the javadoc of that new method should just make clear that the context of the caller is used.
